In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [3]:
# creating tensors
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
TENSOR2 = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                       [[4, 5, 6], [7, 8, 9], [19, 12, 12]]])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[ 4,  5,  6],
         [ 7,  8,  9],
         [19, 12, 12]]])

In [23]:
TENSOR2.shape

torch.Size([2, 3, 3])

### Random tensors


In [24]:
random_tensor = torch.rand(3, 4)

In [26]:
random_tensor

tensor([[0.9072, 0.4990, 0.4724, 0.4433],
        [0.2461, 0.4354, 0.9321, 0.1050],
        [0.2075, 0.8354, 0.6469, 0.9226]])

In [27]:
random_tensor.ndim

2

In [29]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [30]:
### Zeros and ones tensor
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [38]:
### create a range of tensors
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
### create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [42]:
float_32_tensor = torch.tensor([3.0, 5, 9], dtype=None)
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = torch.tensor([3.0, 5, 9], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [44]:
float_32_tensor.type(torch.float16)

tensor([3., 5., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 25., 81.])

### Manipulte tensors
- Addition
- Subtraction
- Multiplication

In [46]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [47]:
tensor * 10

tensor([10, 20, 30])

In [48]:
# Matrix multiplication
tensor

tensor([1, 2, 3])

In [49]:
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
tensor2 = torch.tensor([[1], [2], [3]])

In [51]:
tensor2.shape

torch.Size([3, 1])

In [52]:
tensor.shape

torch.Size([3])

In [54]:
torch.matmul(tensor, tensor2)

tensor([14])

### Min max

In [55]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [58]:
x.min(), x.max()

(tensor(0), tensor(90))

In [60]:
x_float = x.type(torch.float32)
torch.mean(x_float)

tensor(45.)

### Finding the positional min and max

In [65]:
x = torch.arange(1, 100, 10)

In [66]:
x.argmin()

tensor(0)

In [67]:
x.argmax()

tensor(9)

In [68]:
x[0]

tensor(1)

### Reshaping, stacking, sqeezing and unsqueezing tensors