In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


In [2]:
# creating tensors
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR2 = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]],
                       [[4, 5, 6], [7, 8, 9], [19, 12, 12]]])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[ 4,  5,  6],
         [ 7,  8,  9],
         [19, 12, 12]]])

In [16]:
TENSOR2.shape

torch.Size([2, 3, 3])

### Random tensors


In [17]:
random_tensor = torch.rand(3, 4)

In [18]:
random_tensor

tensor([[0.8513, 0.8245, 0.0474, 0.9669],
        [0.0496, 0.6766, 0.9963, 0.3492],
        [0.0808, 0.9651, 0.6280, 0.5207]])

In [19]:
random_tensor.ndim

2

In [20]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [21]:
### Zeros and ones tensor
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [38]:
### create a range of tensors
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
### create tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [42]:
float_32_tensor = torch.tensor([3.0, 5, 9], dtype=None)
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = torch.tensor([3.0, 5, 9], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [44]:
float_32_tensor.type(torch.float16)

tensor([3., 5., 9.], dtype=torch.float16)

In [45]:
float_16_tensor * float_32_tensor

tensor([ 9., 25., 81.])

### Manipulte tensors
- Addition
- Subtraction
- Multiplication

In [46]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [47]:
tensor * 10

tensor([10, 20, 30])

In [48]:
# Matrix multiplication
tensor

tensor([1, 2, 3])

In [49]:
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
tensor2 = torch.tensor([[1], [2], [3]])

In [51]:
tensor2.shape

torch.Size([3, 1])

In [52]:
tensor.shape

torch.Size([3])

In [54]:
torch.matmul(tensor, tensor2)

tensor([14])

### Min max

In [55]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [58]:
x.min(), x.max()

(tensor(0), tensor(90))

In [60]:
x_float = x.type(torch.float32)
torch.mean(x_float)

tensor(45.)

### Finding the positional min and max

In [65]:
x = torch.arange(1, 100, 10)

In [66]:
x.argmin()

tensor(0)

In [67]:
x.argmax()

tensor(9)

In [68]:
x[0]

tensor(1)

### Reshaping, stacking, sqeezing and unsqueezing tensors

In [23]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [26]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [27]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [28]:
# Change the view, view shares same memory as origin tensor
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [29]:
# Change z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [30]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [31]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [32]:
# sqeeze
x = torch.zeros(2, 1, 2, 1, 2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [34]:
y = torch.squeeze(x)
y, y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [36]:
# permute
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channel]
x_original.shape

torch.Size([224, 224, 3])

In [38]:
x_permuted = torch.permute(x_original, (2, 0, 1))
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing with pytorch

In [39]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)

In [41]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [42]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
x[0][0]

tensor([1, 2, 3])

In [44]:
x[0, 0]

tensor([1, 2, 3])

In [45]:
x[0, 0, 0]

tensor(1)

In [46]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [47]:
x[:, 1, 1]

tensor([5])

In [48]:
x[0, 0, :]

tensor([1, 2, 3])